### ISSUE TITLE
Rename repo and change about text?

### ISSUE THREAD

**Issue by jimhester** [RConsortium/S7#244]
As R7 seems to have settled in as the name of the package it is probably time to change the name of this repository and update the text in the about section on GitHub to reflect the current state of things.

**Comment by hadley** [comment]
We're still discussing the name in the working group, so I think it probably needs to stay as is for a while longer.

**Comment by olivroy** [comment]
Should to repo be renamed now? this would facilitate installation with pak

**Comment by jimhester** [comment]
@olivroy it is possible to install with pak when the package name does not equal the repository name using the `pkgname=org/repo` syntax, e.g.

```r
pak::pak("S7=RConsortium/OOP-WG")
```

See https://pak.r-lib.org/reference/pak_package_sources.html#package-names for details.

However I agree it is confusing having this repo having a different name, it makes googling for the repo more challenging, e.g. right now searching for `github S7` the correct repo is the 7th result for me. Using the GitHub search is even worse, using a search term of 'S7' this repo is nowhere in the results I could find.

**Comment by olivroy** [comment]
thanks for the tip!

**Comment by hadley** [comment]
@mmaechler @lawremi any concerns with renaming this repository from OOP-WG to S7?

**Comment by mmaechler** [comment]
not big ones.. I will have to update 2 x 2 symbolic links on my computers..

**Comment by hadley** [comment]
@mmaechler FWIW GitHub will automatically redirect most of the URLs.

**Comment by lawremi** [comment]
Sounds good to me.

**Comment by hadley** [comment]
Done!
