### ISSUE TITLE
Property validation

### ISSUE THREAD

**Issue by kkmann** [RConsortium/S7#275]
Dear all,

I was wondering whether it would be feasible to add optional constraints to property definitions like
```
myclass <- new_class("myclass", properties = list(
  a = class_double(min = 0, na_ok = FALSE)
))
```
Ideally, this would then also be picked up by roxygen2 when documenting class properites. Might be out of scope of a OOP system, but would be kind of handy to have...

Alternatively, do you see a way of standardizing input checking like this in the validator to autogenerate documentation of the constraints?

**Comment by lawremi** [comment]
There could be convenience functions for constructing properties with constraints like this. There's precedent for this sort of thing in property implementations from other languages.

**Comment by hadley** [comment]
We'd also need to add the idea of a property `validator`, but I think that makes sense.

Would be worth considering whether we want to provide canned property classes that represent scalars (but that's a fairly big design problem, so might be worth leaving that to a package).

**Comment by jl5000** [comment]
In my own use of `S7` I would certainly find this very useful. I have implemented a set of validator functions dependent on the type of property:

* Min/max length of atomic vectors/lists
* Min/max character length of strings
* Min/max values of numerics
* Ensuring character properties fit regex patterns
* Ensuring character properties take one of a number of set values
* Ensuring lists contain elements of acceptable classes

Incorporating any of these into `S7` would be useful.
