### ISSUE TITLE
class_null

### ISSUE THREAD

**Issue by jonthegeek** [RConsortium/S7#337]
For method dispatch, `class_missing` doesn't catch `NULL` (which it shouldn't, really). This works, but it doesn't feel quite right: `class_null <- S7::new_S3_class("NULL")`. Should `class_null` be in the base types?

**Comment by jonthegeek** [comment]
(ok, not per se, 'cuz you can't inherit from it... but guidance for how to dispatch for it would be helpful!)

**Comment by hadley** [comment]
You can just use a literal `NULL`:

``` r
library(S7)

g <- new_generic("g", "x")
method(g, NULL) <- function(x) "hello"
g(NULL)
#> [1] "hello"
```

<sup>Created on 2023-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This presumably should be documented somewhere.

**Comment by jonthegeek** [comment]
I could have sworn that didn't work! I wonder what I did. Thanks for the tip! 🙃

**Comment by jonthegeek** [comment]
Aha! This is (equivalent to) what I tried that failed:

``` r
library(S7)

g <- new_generic("g", "x")
method(g, class_missing | NULL) <- function(x) "hello"
#> Error in class_missing | NULL: operations are possible only for numeric, logical or complex types
g(NULL)
#> Error: Can't find method for `g(<NULL>)`.
```

<sup>Created on 2023-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

vs

``` r
library(S7)

g <- new_generic("g", "x")
method(g, class_missing | new_S3_class("NULL")) <- function(x) "hello"
g(NULL)
#> [1] "hello"
```

<sup>Created on 2023-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm going with the separate method for `NULL`, but at least now I can see what tricked me!

**Comment by hadley** [comment]
Ah that I can fix.
