### ISSUE TITLE
length method vs R CMD Check

### ISSUE THREAD

**Issue by jonthegeek** [RConsortium/S7#342]
I'm not sure how to reprex this, because so far I only see the issue inside R CMD Check. This is the warning I get:

> ❯ checking for code/documentation mismatches ... WARNING
> Warning in formals(fun) : argument is not a function

I got it by trying to define a `length` method.

`S7::method(length, rapid) <- function(x) length(x@info)`

It otherwise works with the dev version of S7 (but fails with the CRAN version).

I'm assuming that it's somehow related to length being a primitive rather than an actual S3 generic, but beyond that I'm not sure where to look.

**Comment by hadley** [comment]
Would you mind providing a basic package reprex?

**Comment by jonthegeek** [comment]
Sure, I'll put something together, including the failed check.

**Comment by jonthegeek** [comment]
https://github.com/jonthegeek/S7primitivereprex/actions/runs/6149344761/job/16685015875?pr=1

Somewhat shockingly, I had to include the `R/S7primitivereprex-package.R` file (or possibly specifically the corresponding Rd) to get the error, specifically this piece:

```
#' @keywords internal
"_PACKAGE"
```

I hope that helps track it down!

**Comment by hadley** [comment]
You just need one documentation file to be present, which I guess isn't too surprising given that the error comes from the "checking for code/documentation mismatches" check.

**Comment by hadley** [comment]
I see the same problem when registering a method for `mean()`, so it doesn't appear to be just related to primitives.

You can see the problem more easily with `tools::codoc("S7primitivereprex", ".")`

**Comment by hadley** [comment]
@jonthegeek thanks for trying S7 and reporting these problems!

**Comment by jonthegeek** [comment]
Happy to help! I'd been trying to decide how to structure a data--of-a-particular-shape-focused package, and S7 appeared on CRAN just in time 😊
