### ISSUE TITLE
Abbreviating `str()`

### ISSUE THREAD

**Issue by jl5000** [RConsortium/S7#378]
I have some classes which define many properties, only some of which may have a value. The `str()` function displays all properties, even those of zero-length. Is there a way to only display properties with only a non-zero length?

``` r
library(S7)

test_class <- new_class("test_class",
                        properties = list(
                          x = class_list,
                          y = class_character,
                          z = class_numeric
                        ))

obj <- test_class(z = 1)

str(obj)
#> <test_class>
#>  @ x: list()
#>  @ y: chr(0) 
#>  @ z: num 1

# Desired:
#> <test_class>
#>  @ z: num 1
```

<sup>Created on 2023-11-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Just because the property is empty doesn't mean it doesn't exist, so I think this is the right default display. You can always write your own custom `str()` method.
