### ISSUE TITLE
Default value for new_class(package=)

### ISSUE THREAD

**Issue by lawremi** [RConsortium/S7#411]
Would it not be reasonable to have the `package=` argument to `new_class()` default to  `if (isNamespace(topenv(parent.frame()))) getNamespaceName(topenv(parent.frame()))`? Obviously we would want  to wrap that up in a function to make it easier to read. Passing the package name explicitly seems unnecessary when code is in a package.

**Comment by hadley** [comment]
Yeah, agreed.

**Comment by mmaechler** [comment]
As nobody is disagreeing: The function wrapper could be called  `parent.pkg`  {yes,  with a "."} or `topNamespaceName()`  such that it would be fitting to be added to base R, package `base` (as it fits well with many other ns-utility functions)  or `utils`.

**Comment by t-kalinowski** [comment]
I agree that users shouldn't need to manually provide the package name when calling `new_class()`.

Should we remove the `package` argument entirely and instead infer the package name directly within `new_class()`? Are there any cases where a user might need something other than the actual package name?

**Comment by hadley** [comment]
@t-kalinowski maybe if you've moved the class from one package to another for some reason?

**Comment by mmaechler** [comment]
> I agree that users shouldn't need to manually provide the package name when calling `new_class()`. 

when they develop R code in a package,  yes, indeed.   But also I think we should rather keep the argument for extra flexibility.  Also for developing code outside a package,  possibly still for potentially be added to a package later, etc.

**Comment by lawremi** [comment]
I like the idea of making a base utility. Perhaps we could avoid adding a new function by having `getNamespaceName()` return the current namespace when its `ns` argument is missing?
