### ISSUE TITLE
Suggesting `new_object(..., .list = NULL)`

### ISSUE THREAD

**Issue by dipterix** [RConsortium/S7#415]
I generated a list of property values and found out it's non-trivial to initialize the object from constructor:

```
do.call(new_object, args)
```

gives me error:

```
Caused by error:
! `constructor` must contain a call to `new_object()`
```

Tried as.call, same error...

Is it possible to allow `new_object(.list = args)`, just like many other packages? Maybe I should write a wrapper function instead of using constructor.

**Comment by hadley** [comment]
Yeah, I think a wrapper function would be most appropriate here.
