### ISSUE TITLE
R Consortium September 2024 newsletter: share updates of your working group

### ISSUE THREAD

**Issue by Crosita** [RConsortium/S7#424]
Hi @hadley and team,
I am Coline Zeballos, R Strategy Lead at Roche and member of the R Consortium's Marketing committee.
I am currently collecting working group updates for the RC's quarterly newsletter which will be published at the end of September 2024. Would you like to share a couple of updates for your WG? If so, please do so until Sept 16th. Thank you!
Coline, on behalf of the R Consortium Marketing Committee

**Comment by Crosita** [comment]
Kind reminder to provide a short summary of the latest updates of the S7 working group by Monday Sept 16th for the Q3 newsletter
@t-kalinowski @mmaechler @lawremi @hadley

**Comment by lawremi** [comment]
The OOP working group continues to refine the design and functionality of the package through active discussions within the group and the community at large.
