### ISSUE TITLE
In place mutability of S7 objects

### ISSUE THREAD

**Issue by JosiahParry** [RConsortium/S7#437]
Is there a road map to offer in-place mutation of an S7 object? 

Ideally, I would be able to create a method that update the value of the S7 object while returning another object. 

Here is a bit of a contrived example based on what I'm working on.

```r
my_job <- new_class("my_job", properties = list(status = class_character))

job_status <- new_generic("job_status", "job")

method(job_status, my_job) <- function(job) {
  # do something 
  new_status <- "computing"
  job@status <- new_status

  list(status = "computing", value = "some other derived value")
}
```

**Comment by JosiahParry** [comment]
I do note that the proposal says 

> "We exclude from our scope systems with mutable objects, because immutable objects are generally preferable for interactive data analysis, relegating mutable systems to niche applications, such as GUIs and caching mechanisms."

but does this preclude it from _ever_ being included in S7? 

R6 does not have the niceties of automatic validation which is why I am seeking to use S7—type safety is preferred whenever possible :)

**Comment by hadley** [comment]
We might one day introduce something like R6, but I suspect that's far in the future. For now, you can always make a property that is an environment (although then you do lose all the property validation niceness).

**Comment by t-kalinowski** [comment]
See also: https://github.com/RConsortium/S7/issues/202
