### ISSUE TITLE
bug(?): validators must return NULL

### ISSUE THREAD

**Issue by JosiahParry** [RConsortium/S7#454]
I have observed that validators _must_ return `NULL` otherwise the validators error out. I cannot reason as to why this is. Is this intended behavior? Should the validators always return `self`?  

``` r
params <- S7::new_class(
  "form_params",
  properties = list(params = S7::class_list),
  validator = function(self) {
    lapply(
      self@params,
      rlang:::check_string,
      allow_null = TRUE,
      allow_na = FALSE,
      call = rlang::caller_call()
    )
    # idk why this has to return NULL
    return(NULL)
  }
)

params(list(x = "a"))
#> <form_params>
#>  @ params:List of 1
#>  .. $ x: chr "a"

params <- S7::new_class(
  "form_params",
  properties = list(params = S7::class_list),
  validator = function(self) {
    lapply(
      self@params,
      rlang:::check_string,
      allow_null = TRUE,
      allow_na = FALSE,
      call = rlang::caller_call()
    )
  }
)

params(list(x = "a"))
#> Error: <form_params> object is invalid:
#> - NULL
```

**Comment by hadley** [comment]
That's because they can return a string to more easily create an error.

**Comment by JosiahParry** [comment]
For posterity this comes from: 

> "A validator is a function that takes the object (called self) and returns NULL if its valid or returns a character vector listing the problems." [Classes and objects](https://rconsortium.github.io/S7/articles/classes-objects.html)

Perhaps there can be checks or a more informative error message when the validator returns an unexpected object. I know I will forget about this in a month or so and find this issue. 

The current behavior works to the letter of the law but it does feel like the validator has to be coaxed

**Comment by t-kalinowski** [comment]
I agree, we should emit a better error message if the validator returns something other than `NULL` or a character vector.
