### ISSUE TITLE
Error: trying to get slot "<>" from an object (class "<>") that is not an S4 object 

### ISSUE THREAD

**Issue by MarcellGranat** [RConsortium/S7#462]
Hi,

I just developed a package based on S7, but it turned out that it runs into an error if someone wants to use it with R 4.2.3. But only with that specific version.

The example is truly minimal, only the sample `range` class:
https://github.com/MarcellGranat/tests7

You can try it with posit cloud to investigate it with different R versions.
install.packages("S7")
install.packages("remotes")
remotes::install_github("marcellgranat/tests7")

Thank in advance for suggestions,
Marcell

**Comment by hadley** [comment]
Did you see the advice in https://rconsortium.github.io/S7/articles/packages.html#backward-compatibility ?

**Comment by MarcellGranat** [comment]
> Did you see the advice in https://rconsortium.github.io/S7/articles/packages.html#backward-compatibility ?

That truly solved the issue! Yes, sorry I did not notice this
