### ISSUE TITLE
Recommend CamelCase for class names?

### ISSUE THREAD

**Issue by hadley** [RConsortium/S7#465]
Otherwise when skimming code it's hard to tell the difference between a constructor and a generic.

**Comment by t-kalinowski** [comment]
Since we intend for the first letter to be capitalized (so we can still easily distinguish single-word class names), I wonder if we should refer to it as Pascal case (https://en.wikipedia.org/wiki/Camel_case)

**Comment by hadley** [comment]
IMO camel case is going to be more clear for more users (also I love the file name in that url 😆)

**Comment by t-kalinowski** [comment]
We might also want to add a sentence about this recommendation somewhere in the vignettes and in `?new_class`.
