### ISSUE TITLE
Subsetting S7 objects

### ISSUE THREAD

**Issue by lgatto** [RConsortium/S7#517]
I hope I haven't missed anything obvious in the documentation, but how should I implement `[` for an S7 object? 

I see that there's a `check_subsettable()`  that says that S7 objects are not subsettable and working with trying to work with 

```
method(`[`, ....)
```
complains about not being able to convert `signature` to a valid class.

**Comment by lgatto** [comment]
So here's an example of what I want to do. This works in a script:

```r
library(S7)

Klass <- new_class("Klass",
  properties = list(
    data1 = class_list,
    data2 = class_data.frame))

`[.Klass` <- function(x, i)
    Klass(data1 = x@data1[i],
           data2 = x@data2[i, ])
```

```r
> k <- Klass(data1 = as.list(1:3),
+ data2 = data.frame(x = 1:3, y = letters[1:3]))
> k
<Klass>
 @ data1:List of 3
 .. $ : int 1
 .. $ : int 2
 .. $ : int 3
 @ data2:'data.frame':	3 obs. of  2 variables:
 .. $ x: int  1 2 3
 .. $ y: chr  "a" "b" "c"
> k[1:2]
<Klass>
 @ data1:List of 2
 .. $ : int 1
 .. $ : int 2
 @ data2:'data.frame':	2 obs. of  2 variables:
 .. $ x: int  1 2
 .. $ y: chr  "a" "b"
```

But if I put the same in a package, it fails with `Error in check_subsettable(x) : S7 objects are not subsettable.`.

**Comment by mjskay** [comment]
I think `[` only dispatches on the first argument, so you need <code>method(\`[\`, Klass) <- ...</code>

The error <code>Class specification must be an S7 class object, the result of \`new_S3_class()\`, an S4 class object, or a base class, not a \<list\></code> hints at this obliquely, since single-dispatch methods just take the class, not a list of classes.

**Comment by lgatto** [comment]
Thank you.

**Comment by lawremi** [comment]
Just want to point out for posterity that the S3 syntax for registering the method did not work, because S7 prefixes class names with the package name, so you would need:

```r
`[.pkg::Klass` <- function(x, i)
    Klass(data1 = x@data1[i],
           data2 = x@data2[i, ])
```

Assuming the package is called "pkg".
